create table
  public.nodes (
    id bigint generated by default as identity,
    user_id uuid references auth.users not null,
    created_at timestamp with time zone not null default now(),
    constraint nodes_pkey primary key (id)
  ) tablespace pg_default;


  create table
  public.containers (
    id bigint generated by default as identity,
    user_id uuid references auth.users not null,
    created_at timestamp with time zone not null default now(),
    name text not null,
    image text not null,
    "pullBehaviour" text not null,
    volumes json[] null,
    ports "portSet" [] null,
    node bigint null,
    constraint containers_pkey primary key (id),
    constraint containers_node_fkey foreign key (node) references nodes (id) on update cascade on delete cascade
  ) tablespace pg_default;